### ISSUE TITLE
360 Servo issues

### ISSUE THREAD

**Issue by Bigdog1966** [KitronikLtd/micropython-microbit-kitronik-16-servo-board#1]
Hello,
I have tried the KitronikLtd/micropython-microbit-kitronik-16-servo-board code.
I am trying to make it operate a standard DF15RSMG 360° servo.
I can trim the servo pot to stop moving for 0 position, but very sensitive.
But if I press buttons for 90 or 180 it rotates flat out in the same direction, and when I press for 0 it slowly stops not in the same position each time.
I don't know enough about the code to adjust it to make it work.

Any Help please?

**Comment by Bigdog1966** [comment]
I have found the problem, the DF15RSMG 360° servo is not actually a true servo I have now found out.
It can only be controlled forward & backward with no speed or position control.
I have a new FEETECH FT8346M 91.5g 40kg.cm High Torque 6V-7.4V Metal Steel Gear Digital Servo 360 Degree Rotation, that I will try to control when it arrives.

**Comment by Zaki23madrid** [comment]
how can you control your new feetech servo?

**Comment by Zaki23madrid** [comment]
i mean which micrcontroller are you using?
