### ISSUE TITLE
Initial position (dangerous movement when switching on)

### ISSUE THREAD

**Issue by GuillaumeChretien** [KitronikLtd/micropython-microbit-kitronik-16-servo-board#3]
Hello, when I turn on the microbit and the 16 servo motor board, the servo motors move to an extreme position instead of staying in their current position, this may cause damage to my animatronic. Is this adjustable or configurable? Do I need to modify the .py driver code? PS: Besides this issue, the 16 servo board is great.
Thanks !

**Comment by JackAtKitronik** [comment]
Hi,
The comment in the code said we set all the servos to 90 degrees on initialisation however it actually sets the servos to 0 degrees.
If you would like to set the servos to 90 degrees when initialising then you can change the code like below:
``` python
    def __init__(self):
        ...
        buf[0] = 0xFC
        buf[1] = 0x31
        i2c.write(self.BOARD_1, buf, False)
        buf[0] = 0xFD
        buf[1] = 0x01
        i2c.write(self.BOARD_1, buf, False)
```
If you would like to change the inital angle to something else, then you can use the calculations in the `servo_write` function to set these two registers. The 0xFC register is the low byte and the 0xFD register is the high byte.

Let us know if this solves your issue.
Thanks, Jack

**Comment by GuillaumeChretien** [comment]
Hi,
excuse me for the delay in response. Thank you for your indications which allowed us to initialize the values ​​of the servos without risk of damaging the mechanical part. Thank you for your responsiveness and the quality of your products.
